name: 自动更新直播源

on:
  schedule:
    - cron: '0 6,18 * * *'
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'config/**'
      - '.github/workflows/update-sources.yml'

jobs:
  update-sources:
    name: 更新直播源
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 设置Python环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 创建数据目录
        run: |
          mkdir -p data
          mkdir -p logs

      - name: 生成测试数据
        run: |
          python << 'EOF'
          import json
          import time
          
          # 创建示例直播源
          channels = [
              {"name": "CCTV-1", "url": "http://example.com/cctv1.m3u8", "type": "m3u", "validated": True},
              {"name": "CCTV-2", "url": "http://example.com/cctv2.m3u8", "type": "m3u", "validated": True},
              {"name": "央视频道汇总", "url": "http://example.com/cctv.m3u", "type": "m3u", "validated": True},
          ]
          
          # 保存为JSON
          with open('data/sources.json', 'w', encoding='utf-8') as f:
              json.dump({
                  'timestamp': int(time.time()),
                  'channels': channels
              }, f, ensure_ascii=False, indent=2)
          
          # 生成M3U格式
          m3u_lines = ['#EXTM3U']
          for ch in channels:
              m3u_lines.append(f"#EXTINF:-1,{ch['name']}")
              m3u_lines.append(ch['url'])
          
          with open('data/result.m3u', 'w', encoding='utf-8') as f:
              f.write('\n'.join(m3u_lines))
          
          # 生成TXT格式
          txt_lines = [f"{ch['name']},{ch['url']}" for ch in channels]
          
          with open('data/result.txt', 'w', encoding='utf-8') as f:
              f.write('\n'.join(txt_lines))
          
          print('✅ 数据生成完成')
          EOF

      - name: 检查是否有更改
        id: check_changes
        run: |
          if git diff --quiet data/; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: 配置Git用户信息
        if: always()
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: 提交更改
        if: always()
        run: |
          git add data/
          git commit -m "chore: 自动更新直播源 $(date +%Y-%m-%d\ %H:%M:%S)" || true

      - name: 推送更改
        if: always()
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

      - name: 上传日志
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: update-logs
          path: logs/
          retention-days: 7
